---
- hosts: all
  become: yes
  tasks: 
    - name: wrong_package_install
      apt:
        name: git
        state: present
      ignore_errors: true    
      register: error_message
    - debug:
        var: error_message
    - name: fail if task failed
      when: error_message.failed == true
      fail:
        msg: "the task is failed"  
