---

- hosts: all
  become: yes
  tasks: 
    - name: creating_new_file
      copy:
        dest: /home/ubuntu/newfile1
        content: "Welcome to devops"
    - name: displaying_newfile1_content
      shell: cat /home/ubuntu/newfile1
      register: display_newfile1
    - debug:
        var: display_newfile1.stdout_lines
