---
- hosts: all
  become: yes
  tasks:
    - name: list files
      shell: ls
      notify: listed_files
    - name: today date
      shell: date
      notify: date1
  handlers:
    - name: listed_files
      debug: 
        msg: "listing files"
    - name: date1
      debug:
        msg: "todays date"  
